module.exports = function(grunt) {

    var remapify = require('remapify');

    // Uncomment the next line to report the Grunt execution time (for optimization, etc)
    //require('time-grunt')(grunt);

    // Intelligently lazy-loads tasks and plugins as needed at runtime.
    require('jit-grunt')(grunt);

    var shouldOpen = grunt.option('open');

    // Project configuration.
    grunt.initConfig({

        //Read the package.json
        pkg: grunt.file.readJSON('package.json'),

        /**
         * A code block that will be added to our minified code files.
         * Gets the name and appVersion and other info from the above loaded 'package.json' file.
         * How to use: '<%= banner %>'
         */
        banner: [
            '/*',
            ' * THIS FILE HAS BEEN GENERATED BY AN AUTOMATED TOOL.',
            ' * DO NOT MODIFY DIRECTLY. INSTEAD, MODIFY THE APPROPRIATE SOURCE CODE.',
            ' *',
            ' * <%= pkg.name %> v<%= pkg.version %>',
            ' * <%= pkg.description %>',
            ' * Development By: <%= pkg.developedBy %>',
            ' * Build Date: <%= grunt.template.today("yyyy-mm-dd") %>',
            ' */',
            ''
        ].join('\n'),

        /**
         * Deletes our production folder before we create a new build.
         */
        clean: {
            web: ['web']
        },

        /**
         * Compiles the Handlebars templates into pre-compiled handlebars templates
         */
        handlebars: {
            compile: {
                options: {
                    amd: ['handlebars'],
                    namespace: 'JST',
                    // Registers all files that start with '_' as a partial.
                    partialRegex: /^_/,
                    // Shortens the file path for the templates.
                    processName: function(filePath) { // input:  src/templates/_header.hbs
                        return filePath.slice(filePath.indexOf('template'), filePath.lastIndexOf('.')); // output: templates/_header
                    },
                    // Shortens the file path for the partials.
                    processPartialName: function(filePath) { // input:  src/templates/_header.hbs
                        return filePath.slice(filePath.indexOf('template'), filePath.lastIndexOf('.')); // output: templates/_header
                    }
                },
                files: {
                    'src/assets/scripts/templates.js': 'src/assets/templates/**/*.hbs'
                }
            }
        },

        /**
         * Copy and needed files to the web folder.
         */
        copy: {
            styles: {
                files: [{
                    expand: true,
                    cwd: 'src/',
                    dest: 'web/',
                    src: [
                        'index.html',
                        'assets/media/**',
                        'assets/vendor/todomvc-common/bg.png',
                        'assets/{styles,vendor}/**/*.css',
                        'assets/{scripts,vendor}/**/*.js'
                    ]
                }]
            }
        },

        connect: {
            server: {
                options: {
                    port: 31415,
                    protocol: 'http',
                    base: 'web/',
                    livereload: true,
                    open: shouldOpen ? true : false // opens a tab in your default browser e.g. grunt launch --open
                }
            }
        },

        /**
         * Watches files and will run task(s) when files are changed. It will also reload/refresh the browser.
         */
        watch: {
            markup: {
                options: {
                    livereload: true
                },
                files: ['src/**/*.html', 'src/**/*.css'],
                tasks: ['copy']
            },
            script: {
                options: {
                    livereload: true
                },
                files: ['src/**/*.js'],
                tasks: ['copy']
            },
            templates: {
                options: {
                    livereload: true
                },
                files: ['src/**/*.hbs'],
                tasks: ['handlebars']
            }
        }
    });

    /**
     * Grunt tasks:
     *
     * grunt            (Will build code for production)
     * grunt launch     (Will build code for production and open the browser with the application)
     */
    grunt.registerTask('default', [
        'clean',
        'handlebars',
        'copy'
    ]);

    grunt.registerTask('launch', [
        'default',
        'connect',
        'watch'
    ]);

};
