module.exports = function(grunt) {

    // -- Plugins --------------------------------------------------------------

    // Uncomment the next line to report the Grunt execution time (for optimization, etc)
    //require('time-grunt')(grunt);

    // Intelligently lazy-loads tasks and plugins as needed at runtime.
    require('jit-grunt')(grunt)({ customTasksDir: 'tasks' });

    // Project configuration.
    grunt.initConfig({

        //Read the package.json
        pkg: grunt.file.readJSON('package.json'),

        /**
         * A code block that will be added to our minified code files.
         * Gets the name and appVersion and other info from the above loaded 'package.json' file.
         * How to use: '<%= banner %>'
         */
        banner: [
            '/*',
            ' * THIS FILE HAS BEEN GENERATED BY AN AUTOMATED TOOL.',
            ' * DO NOT MODIFY DIRECTLY. INSTEAD, MODIFY THE APPROPRIATE SOURCE CODE.',
            ' *',
            ' * <%= pkg.name %> v<%= pkg.version %>',
            ' * <%= pkg.description %>',
            ' * Development By: <%= pkg.developedBy %>',
            ' * Build Date: <%= grunt.template.today("yyyy-mm-dd") %>',
            ' */',
            ''
        ].join('\n'),

        /**
         * Deletes our production folder before we create a new build.
         */
        clean: {
            before: ['web'],
            after: ['.tmp']
        },

        /**
         * Copy and needed files to the web folder.
         */
        copy: {
            styles: {
                files: [{
                    expand: true,
                    cwd: 'src/',
                    dest: 'web/',
                    src: [
                        'index.html',
                        'assets/media/**',
                        'assets/vendor/todomvc-common/bg.png',
                        'assets/{styles,vendor}/**/*.css',
                        'assets/vendor/jquery/dist/jquery.js',
                        '!assets/vendor/structurejs/**'
                    ]
                }]
            }
        },

        /**
         * Merge and files with the generated Browserify file.
         */
        concat: {
            options: {
                separator: ';'
            },
            dist: {
                src: [
                    'src/assets/vendor/handlebars/handlebars.runtime.min.js',
                    'src/assets/scripts/precompiledJst.js',
                    'web/assets/scripts/main.js'
                ],
                dest: 'web/assets/scripts/main.js'
            }
        },

        /**
         * Watches files and will run task(s) when files are changed. It will also reload/refresh the browser.
         */
        watch: {
            markup: {
                options: {
                    livereload: true
                },
                files: ['src/**/*.html', 'src/**/*.css'],
                tasks: ['copy']
            },
            script: {
                options: {
                    livereload: true
                },
                files: ['src/**/*.ts'],
                tasks: ['browserify', 'copy', 'concat']
            },
            templates: {
                options: {
                    livereload: true
                },
                files: ['src/**/*.hbs'],
                tasks: ['handlebars']
            }
        }
    });

    /**
     * Grunt tasks:
     *
     * grunt            (Will build code for production)
     * grunt launch     (Will build code for production and open the browser with the application)
     */
    grunt.registerTask('default', [
        'clean:before',
        'buildTypeScript',
        'precompileJst',
        'copy',
        'concat',
        'clean:after'
    ]);

    grunt.registerTask('launch', 'Runs build, launches http-server, watches for file changes', [
        'default',
        'connectHttp',
        'watch'
    ]);

    grunt.loadNpmTasks('grunt-contrib-watch');

};
